version: "3.5"

services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}-nginx"
    working_dir: /var/www
    restart: always
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
    depends_on:
      - php
      - postgres

  postgres:
    image: postgres:latest
    container_name: "${PROJECT_NAME}-postgres"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgres
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        XDEBUG_PORT: ${XDEBUG_PORT:-9001}
        USER_UID: ${USER_UID:-1000}
    container_name: "${PROJECT_NAME}-php"
    working_dir: /var/www
    restart: always
    volumes:
      - .:/var/www
    environment:
      - DOCKER_UID=1000
      - DOCKER_GID=1000
